### ISSUE TITLE
update it in PyPi

### ISSUE THREAD

**Issue by jabbalaci** [morninj/django-email-obfuscator#5]
Hi,

Thanks for the obfuscator. I noticed that you have an older version in PyPi that doesn't work correctly because of wrong string formatting. It took me some while to figure out the problem. I wanted to send a pull request but then I saw it was corrected here in your repo...

BTW, you can write simply

```
return ''.join(['&#{0};'.format(str(ord(char))) for char in value])
```

, the `:s` in `{0:s}` is not necessary.

Summary: PyPi contains an old and wrong version, please update it.

Best,

Laszlo

**Comment by ZobairAlijan** [comment]
Hi,
I spent 1 hour to figure out why obfuscate did not work. I found out that you were using wrong string formatting(old version). if you could update that, it would be really helpful for the next guy. Thank you

**Comment by shulcsm** [comment]
ping

**Comment by jabbalaci** [comment]
I indicated this problem last August, got no reply since then. I guess this project is abandoned. I think someone should fork it and upload to PyPI under a different (though similar) name.

**Comment by morninj** [comment]
Sorry for the slow reply! For some reason, I didn't get email notifications for this issue. It should be resolved.
